name: Functions

on: [push]

jobs:
  functions:
    runs-on: ubuntu-latest 
    steps:
      - name: dump  
        run: |
          echo ${{ contains( 'helo', 'll' )}}
          echo ${{ startsWith( 'helo', 'he' )}}
          echo ${{ endsWith( 'helo', 'lo' )}}
          echo ${{ format( 'Hello {0} {1} {2}', 'World', '!', '!' )}}
