on: 
  pull_request:
    branches:
      - master
      - 'feature/**'
      - '!feature/featC' # this pattern will ignore pull requests on a specific branch
    tags:
      - v1.*
    paths:
      - '**.js' # rodará sempre que houver um arquivo javascript no repositório
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo teste
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm  -v
          python --version
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash 
