on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo teste
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm  -v
          python --version

